[package]
name = "cody-nelson/t"
description = "A Runtime Typechecker for Roblox"
version = "1.0.0"
license = "MIT"
authors = ["Osyris", "Schematics"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["lib", "lib/init.lua", "default.project.json", "LICENSE", "README.md", "wally.toml", ".luaurc"]

[dependencies]
